<?php  echo $this->doctype()?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Ca doan Maria Trinh Vuong '. $this->translate('Giao xu Thai Ha'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styles/layout.css')
                        ->prependStylesheet($this->basePath() . '/css/styles/forms.css')
                        ->prependStylesheet($this->basePath() . '/css/styles/mobile.css')
                        ->prependStylesheet($this->basePath() . '/css/styles/navi.css')
                        ->prependStylesheet($this->basePath() . '/css/styles/tables.css')
                        ->prependStylesheet($this->basePath() . '/css/styles/featured_slide.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            // ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/scripts/galleryviewthemes/jquery.galleryview.2.1.1.min.js')
            ->prependFile($this->basePath() . '/js/scripts/galleryviewthemes/jquery.timers.1.2.js')
            ->prependFile($this->basePath() . '/js/scripts/galleryviewthemes/jquery.easing.1.3.js')
            ->prependFile($this->basePath() . '/js/scripts/galleryviewthemes/jquery.galleryview.setup.js')
            ->prependFile($this->basePath() . '/js/jquery.min.blog.js')
        ; ?>

    </head>
    <body id="top">
    <div class="wrapper col0">
    	<div id="topline">
		    <p>Tel: 0912 464 373 | Mail: mariatrinhvuong@gmail.com</p>
		    <ul>
		      <li><a href="#">Đăng nhập</a></li>
		      <li><a href="#">Đăng ký</a></li>
		      
		    </ul>
		    <br class="clear" />
  		</div>
    </div>
    <div class="wrapper">
	 <div id="header">
	    <div class="fl_left">
		    <h1><a href="index.html"><strong>M</strong>aria <strong>T</strong>rinh <strong>V</strong>ương </a></h1>
		    <p>Suốt cuộc đời tôi xin hát mừng Chuá, sống bao lâu nguyện đàn ca kính Chúa trời.</p>
		    </div>
		    <!-- <div class="fl_right"><a href="#"><img src="images/demo/468x60.gif" alt="" /></a></div> -->
		    <br class="clear" />
	  	</div>
	</div>
   	<div class="wrapper col2">
	  	<div id="topbar">
	    <div id="topnav">
	      <ul>
	        <li class="active"><a href="<?php echo $this->url('home')?> ">Trang chủ</a></li>
	        <li><a href="<?php echo $this->url('post') ?>">Tin tức</a></li>
	        
	        <!-- <li><a href="#">DropDown</a>
	          <ul>
	            <li><a href="#">Link 1</a></li>
	            <li><a href="#">Link 2</a></li>
	            <li><a href="#">Link 3</a></li>
	          </ul>
	        </li> -->
	        <!-- <li class="last"><a href="#">A Long Link Text</a></li> -->
	      </ul>
	    </div>
	    <!-- <div id="search">
	      <form action="#" method="post">
	        <fieldset>
	          <legend>Site Search</legend>
	          <input type="text" value="Search Our Website&hellip;"  onfocus="this.value=(this.value=='Search Our Website&hellip;')? '' : this.value ;" />
	          <input type="submit" name="go" id="go" value="Search" />
	        </fieldset>
	      </form>
	    </div> -->
	    <br class="clear" />
	  	</div>
		</div>
        
            <?php echo $this->content; ?>
    

    <div class="wrapper">
	  <div id="socialise">
	    <ul>
	      <li><a href="#"><img src="<?php echo $this->basePath() ?>/img/facebook.gif" alt="" /><span>Facebook</span></a></li>
	      <li><a href="#"><img src="<?php  echo $this->basePath()?>/img/rss.gif" alt="" /><span>FeedBurner</span></a></li>
	      <li class="last"><a href="#"><img src="<?php echo $this->basePath()?>/img/twitter.gif" alt="" /><span>Twitter</span></a></li>
	    </ul>
	    <div id="newsletter">
	      <h2>NewsLetter Sign Up !</h2>
	      <p>Please enter your Email and Name to join.</p>
	      <form action="#" method="post">
	        <fieldset>
	          <legend>Digital Newsletter</legend>
	          <div class="fl_left">
	            <input type="text" value="Enter name here&hellip;"  onfocus="this.value=(this.value=='Enter name here&hellip;')? '' : this.value ;" />
	            <input type="text" value="Enter email address&hellip;"  onfocus="this.value=(this.value=='Enter email address&hellip;')? '' : this.value ;" />
	          </div>
	          <div class="fl_right">
	            <input type="submit" name="newsletter_go" id="newsletter_go" value="&raquo;" />
	          </div>
	        </fieldset>
	      </form>
	      <p>To unsubsribe please <a href="#">click here &raquo;</a>.</p>
	    </div>
	    <br class="clear" />
	  </div>
	</div>
	<!-- ####################################################################################################### -->
	<div class="wrapper col8">
	  <div id="copyright">
	    <p class="fl_left">Copyright &copy; 2015 - All Rights Reserved - <a href="#">mariatrinhvuong.org</a></p>
	    <p class="fl_right">Design by <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">Hải</a></p>
	    <br class="clear" />
	  </div>
	</div>
    </body>
</html>