<div class="wrapper">
  <div class="container">
    <div class="content">
      <div id="featured_slide">
        <ul id="featurednews">
        <?php for($i=0;$i<$sum;$i++): ?>
          <?php foreach (${'postnewests' . $i} as $postnewest) :?>
          <li><img height="280" width="600" src="<?php echo $this->thumbnail_helper($postnewest->getContent()) ?>" alt="" />
            <div class="panel-overlay">
              <h2><?php echo $postnewest->getTitle() ?></h2>
              <p><?php echo $this->body_helper($postnewest->getContent(),100) ?><br />
                <a href="<?php echo $this->url('post',array('action'=>'view','id'=>$postnewest->getId(),'slug'=>$postnewest->getSlug())) ?>">Continue Reading &raquo;</a></p>
            </div>
          </li>
          <?php endforeach; ?>
          <?php endfor;?>
        </ul>
      </div>
    </div>
    <div class="column">
      <ul class="latestnews">
        <?php for($i=0;$i<$sum;$i++): ?>
        <?php foreach (${'postnewests' . $i} as $postnewest) :?>
        <li><img width="100" height="100" src="<?php echo $this->thumbnail_helper($postnewest->getContent()) ?>" alt="" />
        <p><strong><a href="<?php echo $this->url('post',array('action'=>'view','id'=>$postnewest->getId(),'slug'=>$postnewest->getSlug())) ?>"><?php echo $postnewest->getTitle() ?></a></strong> <?php echo $this->body_helper($postnewest->getContent(),100) ?></p>
        </li>
        <?php endforeach; ?>
        <?php endfor;?>
      </ul>
    </div>
    <br class="clear" />
  </div>
</div>