
<?php foreach ($categories as $category) :?>
	<h3><a href="<?php echo $this->url('category',array('action'=>'viewposts','id'=>$category->getId(),'slug'=>$category->getSlug()))?>"><?php echo $category->getName(); ?></a></h3>
<?php endforeach; ?>

<h3><a href="<?php echo $this->url('post',array('action'=>'add')) ?>">Add new Post</a></h3>

<?php foreach ($posts as $post) : ?>
	<h1><a href="<?php echo $this->url('post', array('action'=>'view','id'=>$post->getId(),'slug'=>$post->getSlug())) ?>"><?php echo $post->getTitle()?></a></h1>
	<img src="<?php echo $this->thumbnail_helper($post->getContent()) ?>"/>
	<p><?php echo $this->body_helper($post->getContent(), 100)?></p>
	<br>
	<a href="<?php echo $this->url('post',array('action'=>'edit','id'=>$post->getId(),'slug'=>$post->getSlug()))?>">Edit</a> |
	<a href="<?php echo $this->url('post', array('action'=>'delete','id'=>$post->getId(),'slug'=>$post->getSlug()))?>" onclick="return confirm('Are u sure??')">Delete</a>
<?php endforeach;?>