
<?php foreach ($categories as $category) :?>
	<h3><a href="<?php echo $this->url('category',array('action'=>'viewposts','id'=>$category->getId(),'slug'=>$category->getSlug()))?>"><?php echo $category->getName(); ?></a></h3>
<?php endforeach; ?>

<h3><a href="<?php echo $this->url('post',array('action'=>'add')) ?>">Add new Post</a></h3>

<?php foreach ($posts as $post) : ?>
	<h1><a href="<?php echo $this->url('post', array('action'=>'view','id'=>$post->getId(),'slug'=>$post->getSlug())) ?>"><?php echo $post->getTitle()?></a></h1>
	<img  style="width:200px;height:200px" src="<?php echo $this->thumbnail_helper($post->getContent()) ?>"/>
	<p><?php echo $this->body_helper($post->getContent(), 100)?></p>
	<br>
	<a href="<?php echo $this->url('post',array('action'=>'edit','id'=>$post->getId(),'slug'=>$post->getSlug()))?>">Edit</a> |
	<a href="<?php echo $this->url('post', array('action'=>'delete','id'=>$post->getId(),'slug'=>$post->getSlug()))?>" onclick="return confirm('Are u sure??')">Delete</a>
<?php endforeach;?>

<div class="wrapper">
  <div class="container">
    <div class="content">
      <div id="featured_slide">
        <ul id="featurednews">
          <li><img src="images/demo/1.gif" alt="" />
            <div class="panel-overlay">
              <h2>Nullamlacus dui ipsum</h2>
              <p>Temperinte interdum sempus odio urna eget curabitur semper convallis nunc laoreet.<br />
                <a href="#">Continue Reading &raquo;</a></p>
            </div>
          </li>
          
        </ul>
      </div>
    </div>
    <div class="column">
      <ul class="latestnews">
        <li><img src="images/demo/100x100.gif" alt="" />
          <p><strong><a href="#">Indonectetus facilis leo.</a></strong> Nullamlacus dui ipsum cons eque loborttis non euis que morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque.</p>
        </li>
        <li><img src="images/demo/100x100.gif" alt="" />
          <p><strong><a href="#">Indonectetus facilis leo.</a></strong> Nullamlacus dui ipsum cons eque loborttis non euis que morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque.</p>
        </li>
        <li class="last"><img src="images/demo/100x100.gif" alt="" />
          <p><strong><a href="#">Indonectetus facilis leo.</a></strong> Nullamlacus dui ipsum cons eque loborttis non euis que morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque.</p>
        </li>
      </ul>
    </div>
    <br class="clear" />
  </div>
</div>